---
service:
  family:
    - core
    - webui
  name: genesys-cloud-client-logger-webui
  blueprint: webUi
  team: Client Streaming and Signaling
  jiraProjectKey: STREAM
  pmContact: alan.lanteigne@genesys.com
  qaContact: sohel.patel@genesys.com
  gitDefaultBranch: develop
costAllocation:
  productGroup: Platform
  businessUnit: CX
  consumedBy:
    - CX
