export const STRING_SIZE_7546_BYTES = `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus tempus augue eu neque euismod, a porta odio fermentum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent et sapien rutrum, rhoncus sapien eu, aliquet ex. Proin at lectus pharetra, dapibus ante eget, auctor augue. Vivamus molestie velit eget vestibulum volutpat. Sed sagittis metus et ullamcorper pulvinar. Fusce nisi leo, commodo at faucibus nec, mollis a mauris. Maecenas turpis libero, consectetur et laoreet sit amet, accumsan vitae tellus. Nam fermentum lacus arcu, a sodales quam aliquam eget. Donec convallis felis nec turpis eleifend, sit amet commodo mauris vestibulum. Morbi tempor diam sit amet aliquam varius. Sed fringilla ligula ac erat luctus congue. Aenean nec malesuada elit, ut pellentesque lectus. Pellentesque eget imperdiet odio.

Aliquam varius ultrices dolor, quis luctus risus commodo in. Fusce ornare luctus erat, vitae porta sapien. Duis at ultricies dolor. Nunc cursus, eros at eleifend hendrerit, lorem ligula ornare ex, et accumsan ligula quam vel tortor. Integer sit amet felis felis. Donec sed bibendum tortor, vel egestas metus. Aenean luctus viverra nisi eu placerat. Aliquam orci erat, aliquam a urna scelerisque, maximus molestie mi. Nulla eget arcu risus. Morbi a tortor velit.

Curabitur venenatis porttitor placerat. Nulla ornare odio placerat ipsum semper luctus. Morbi viverra eros justo, eu bibendum sapien lobortis et. Vestibulum ultricies sollicitudin malesuada. Nunc iaculis facilisis laoreet. Proin bibendum justo et posuere aliquam. Fusce mollis in ipsum vel accumsan. Cras tincidunt est nibh, a ultrices dolor vulputate vel. Ut vehicula tellus non dictum scelerisque. Fusce facilisis massa eget lacus posuere, vel finibus leo finibus. Integer aliquet justo vitae rhoncus efficitur. Quisque consectetur interdum risus quis rhoncus. Nullam maximus, metus vitae finibus facilisis, ante tortor semper purus, et accumsan sem purus vehicula nibh.

Pellentesque at neque tincidunt, malesuada libero vel, ornare augue. Sed fermentum urna in ligula eleifend porta. Fusce magna justo, vestibulum et gravida vitae, egestas ac neque. Suspendisse sed dui ac dui feugiat condimentum. Fusce vestibulum risus ac varius sodales. Etiam condimentum, massa in egestas suscipit, lacus sem lobortis est, vel suscipit enim urna vel mi. Integer blandit laoreet lacus a ullamcorper. Sed scelerisque ante eu condimentum tincidunt. Duis eu lobortis elit. Duis auctor consequat ante in vulputate. Donec sit amet justo in lorem sollicitudin ultricies ac a ipsum.

Nam non arcu in leo suscipit cursus id vitae felis. Donec ullamcorper commodo dui a dictum. Sed tincidunt non augue at molestie. Duis quis urna ac ipsum volutpat porta ut vel dolor. Vivamus porta congue erat, vel imperdiet risus facilisis sit amet. Mauris auctor in sapien a tempus. Proin eget nisl at tellus auctor lobortis eu nec nibh. Nullam malesuada mauris ut massa feugiat, eget interdum tellus tempor. Sed vel diam lacus. Curabitur ut nisl non magna tristique pharetra. Aenean nec est sapien. Curabitur diam purus, viverra et nisi id, eleifend ultricies arcu. In mattis sit amet lectus quis semper.

Duis lacus massa, rhoncus vitae erat in, volutpat venenatis erat. Phasellus dignissim mi a pellentesque accumsan. In in magna eu mi pulvinar vulputate tempor sit amet libero. Sed feugiat elementum semper. Nunc ut nibh purus. Phasellus varius condimentum nulla, vel consectetur neque. Curabitur nec euismod nisl, non commodo elit.

Maecenas hendrerit elit in quam suscipit commodo. Sed sed risus ac augue luctus tempus. Ut feugiat posuere elit ut consectetur. Nullam scelerisque interdum laoreet. Pellentesque sagittis mauris id turpis feugiat, quis volutpat odio ultrices. Curabitur quis ex et eros lacinia pretium. Donec congue dolor quis purus dictum euismod. Duis consequat, nisi sit amet accumsan sodales, nisl mi tincidunt lectus, eget varius odio tortor vel ante. Suspendisse at auctor urna. Nunc quis cursus est. Morbi fermentum dolor orci, eget posuere ligula euismod vitae. Maecenas dictum orci vel massa vulputate, sit amet rhoncus tellus aliquet. Praesent diam erat, maximus sed lobortis sit amet, auctor a nibh. Donec ultrices dapibus elementum.

Aliquam mattis commodo leo at scelerisque. Morbi pellentesque fermentum tortor, vel cursus mauris fermentum et. In porttitor erat ligula, sed tempus risus convallis ut. Suspendisse fringilla vestibulum ligula quis iaculis. Nulla tempus justo vitae maximus maximus. Praesent vitae odio aliquet, posuere neque vitae, consequat ex. Cras vulputate tortor fermentum, congue quam sed, condimentum lacus.

Nam feugiat lorem vitae vehicula convallis. Quisque vitae ipsum elementum, scelerisque justo non, imperdiet purus. Mauris eleifend turpis in ultricies pharetra. Proin volutpat quam eget augue semper, non consequat nunc blandit. Nullam ac imperdiet nisi. Nullam sed tellus non odio sodales suscipit et sed lectus. Fusce rhoncus sagittis gravida. Morbi faucibus dignissim pharetra. Curabitur at libero egestas, sollicitudin enim non, lacinia nibh. Mauris vitae sapien urna. Duis at vestibulum erat.

Donec pretium mattis metus, eu aliquet purus semper in. Aenean in nulla ullamcorper mi condimentum lacinia. Quisque lobortis, massa et scelerisque volutpat, elit tellus ultrices neque, in maximus augue nibh quis enim. Ut mauris mauris, porta eu tempor a, feugiat sit amet mauris. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus lacinia vulputate ex nec iaculis. Praesent at neque quis est malesuada lacinia. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Suspendisse id ultrices ante, sed porta ante. Ut eu vulputate arcu. Nulla convallis tincidunt tempus. Maecenas posuere felis risus, vitae dapibus eros gravida in. Sed aliquam posuere pulvinar. Vivamus commodo arcu dui, nec lacinia eros dignissim sit amet. Suspendisse eu felis vitae ante euismod iaculis. Aliquam et dolor eget urna laoreet fringilla ac nec magna.

Curabitur congue nibh vitae tortor vulputate, et sodales augue tincidunt. Etiam et vestibulum purus. Aenean ante nibh, varius eget leo sit amet, accumsan interdum diam. Vivamus vel erat aliquam, fringilla arcu in, luctus mi. Nam tristique lacus quam, sed mollis quam auctor fringilla. Nullam scelerisque metus magna, vitae semper purus aliquet eget. Pellentesque non sollicitudin odio, id facilisis ante. Vestibulum sollicitudin urna sit amet lacus volutpat, id vulputate metus dignissim. Maecenas cursus dolor pellentesque pulvinar elementum. Vestibulum felis est, venenatis sit amet maximus sit amet, volutpat non orci. Nunc pulvinar neque in risus lacinia dapibus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Curabitur dignissim orci eu libero tincidunt, a ultrices elit sollicitudin.

Aliquam odio lectus, fermentum sed vehicula vitae, rutrum in neque. Nulla dapibus, leo eget malesuada egestas, diam nibh lacinia lacus, vitae ornare elit urna et nibh. Phasellus vitae vulputate orci. Nunc nec sollicitudin tortor. Aenean eu nunc arcu. Suspendisse varius, lacus sit amet finibus tempus, mauris ligula finibus neque, eget viverra lorem lorem a mi. Nullam non massa tempor, volutpat odio at, efficitur risus. Nunc tristique et turpis ac suscipit. Pellentesque ac fermentum diam. Cras molestie finibus nibh non egestas. Integer fermentum metus in interdum interdum. Aenean ac ligula gravida, cursus dui amet.`;


export const TOO_LARGE_LOG_MESSAGE = `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque quis ante a diam vulputate convallis ut eu libero. Praesent tristique libero quis interdum dignissim. Curabitur porta ipsum gravida, lacinia tortor non, facilisis erat. Etiam imperdiet mi et pellentesque aliquet. Duis cursus porttitor sem at fringilla. Aliquam elementum erat lectus. Vivamus dictum pretium nulla quis porta. In magna nisl, ullamcorper in congue consectetur, aliquam vitae quam. Pellentesque convallis consectetur dolor sit amet bibendum. Cras blandit mi a pulvinar facilisis.

Etiam iaculis lorem eget elit faucibus, id tempus lorem vehicula. Donec in placerat neque, eget viverra purus. Praesent posuere luctus ligula, at porta arcu pulvinar quis. Donec vulputate ipsum et tristique luctus. Curabitur efficitur eget massa id venenatis. Quisque non imperdiet ipsum. Cras dapibus erat nulla, ac luctus lorem ullamcorper eu. Nulla vel nibh gravida, imperdiet leo id, efficitur neque. Nulla facilisi. Curabitur pulvinar purus id tincidunt euismod. Ut accumsan, leo euismod laoreet semper, tellus velit sodales est, quis ullamcorper ante leo vel odio. Nam eget dui ultrices, ornare leo in, lacinia ipsum. Suspendisse scelerisque, orci in ornare lobortis, turpis lorem gravida urna, nec scelerisque turpis metus non urna. Phasellus nunc massa, dignissim id laoreet ac, tristique id turpis.

Suspendisse ipsum velit, tincidunt non maximus id, aliquet eget turpis. Phasellus eget tellus et dolor laoreet elementum. Nunc nec efficitur felis. Integer et sodales magna, non rhoncus odio. Duis odio augue, feugiat et urna quis, euismod dignissim ligula. Fusce lacinia massa eget accumsan scelerisque. Sed nisl lacus, suscipit ac sem quis, dictum euismod leo. Proin volutpat feugiat diam, a sagittis justo dictum eget. Nam commodo ullamcorper est, quis placerat ligula tincidunt vel. Donec at elit eleifend, ultricies risus ut, pretium ex. Maecenas feugiat tempus libero ac gravida.

In interdum elementum ex eget condimentum. Phasellus ultrices diam orci, et iaculis augue fringilla et. Suspendisse lobortis ultricies felis condimentum volutpat. Phasellus pellentesque vestibulum iaculis. Aenean a mi sit amet massa tristique convallis in a risus. Donec sollicitudin tincidunt molestie. Aenean nibh massa, cursus eget sapien nec, vehicula mollis ante.

Morbi volutpat ex vitae est pellentesque fringilla. In pretium scelerisque nulla, eget sollicitudin arcu gravida in. Maecenas ut odio malesuada, aliquet sapien sed, suscipit turpis. Nam blandit vehicula tellus eu accumsan. Suspendisse ullamcorper mi sed mauris pharetra, ac placerat augue ultrices. Integer sollicitudin maximus lectus, in faucibus risus molestie facilisis. Donec nec ex justo.

Aenean vehicula, arcu laoreet laoreet vestibulum, odio nunc lobortis dolor, sed suscipit turpis lorem a risus. Quisque lacus elit, pellentesque ac consequat vel, tempus vitae velit. Donec placerat, tortor eu eleifend commodo, magna risus tempor neque, eu vehicula lectus nulla quis nulla. Donec eget tortor eget ex fringilla varius. Nulla pellentesque lobortis bibendum. Curabitur bibendum consequat maximus. Ut vitae mauris sollicitudin, condimentum massa vitae, facilisis justo. Morbi egestas lobortis quam nec pretium. Etiam efficitur mattis pulvinar. Aliquam nisl nulla, pretium id sagittis eu, blandit sed felis. Maecenas cursus accumsan dui, id fringilla ante tincidunt eu. In a porta felis.

Proin pulvinar lobortis sapien, at rutrum arcu commodo vitae. Sed accumsan pharetra purus mattis ornare. Sed viverra lacus ac sapien semper cursus. Morbi quis dolor tellus. Praesent pretium, felis et fringilla suscipit, nulla nunc fringilla ligula, et placerat odio mauris sit amet dolor. Aenean elit enim, cursus mattis molestie sed, fermentum eget lacus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec enim velit, sodales eget lectus ac, maximus porta felis. In iaculis enim ac risus mattis, id lobortis ipsum porta. Cras cursus sagittis purus a efficitur. Vestibulum et magna in mi vehicula pulvinar. Donec sit amet interdum ex, et bibendum elit. Curabitur dignissim egestas justo. Morbi ultricies faucibus dolor ut pellentesque. Aliquam tempus non neque non pretium.

Donec augue tellus, finibus ut lacus vel, porta fermentum eros. Nam consectetur bibendum turpis ut pretium. Integer orci sem, luctus sit amet porttitor ac, eleifend sed libero. Sed dignissim elit tristique, scelerisque mauris sed, ultrices neque. Suspendisse venenatis dignissim ex, quis dignissim massa euismod eu. Praesent elementum, turpis quis feugiat cursus, turpis tortor consequat neque, non tincidunt ligula arcu in eros. Quisque eu leo lectus. Donec auctor, velit ut tincidunt luctus, lacus sem facilisis ipsum, tincidunt vulputate metus neque sed augue. Aenean rhoncus, velit at volutpat congue, lacus nisi rutrum leo, quis scelerisque tellus lacus eget odio.

Quisque ut lacus rhoncus, euismod dui a, suscipit ligula. Donec sit amet porta metus, sit amet vestibulum lectus. In hac habitasse platea dictumst. Praesent non fermentum est. Integer tincidunt est eu finibus posuere. Cras elementum feugiat arcu at maximus. Vivamus iaculis finibus auctor. Fusce in nunc auctor, venenatis urna ut, molestie ex. Sed elit neque, finibus sed sem laoreet, viverra fermentum metus. Quisque venenatis, nibh eu congue placerat, dui nisl pellentesque mi, at imperdiet felis arcu at ligula. Morbi vitae diam lectus. Suspendisse eget sapien lacinia, vestibulum velit maximus, finibus tellus. Ut nec pellentesque purus. Nullam maximus scelerisque massa ac iaculis.

Ut vel lectus eros. Maecenas maximus egestas est non imperdiet. Nulla tristique ex in lorem consequat ornare. Aenean at nulla ipsum. Morbi neque nisi, sodales in porttitor nec, tempor vitae ante. Pellentesque suscipit, nibh iaculis mollis rhoncus, justo lorem commodo orci, non eleifend felis odio vitae nibh. Proin gravida mattis orci sit amet tincidunt. Duis quis cursus justo. Duis pharetra scelerisque ligula vitae consequat. Etiam tempor, quam eu condimentum volutpat, quam urna feugiat ipsum, eget fringilla mauris metus vel nisi.

Integer eget consectetur risus. Ut eget ex ut augue imperdiet pulvinar ac a enim. In vulputate molestie felis eu porttitor. Nullam feugiat ultricies mauris, in condimentum elit blandit ac. Nulla nunc mauris, accumsan ac ligula eu, malesuada viverra purus. Pellentesque viverra eros eget mollis bibendum. Pellentesque accumsan vitae odio non ultricies. Morbi eget odio ac justo vehicula pulvinar eu non dolor. Suspendisse pulvinar sollicitudin gravida. Etiam vel mi ultrices, lacinia arcu ac, facilisis leo. Proin a velit vitae ante porttitor molestie. Donec ut dictum sapien. Vestibulum eget ipsum et sapien gravida faucibus non ac nisi. Ut at nibh odio.

Fusce vel sem porta leo pulvinar finibus id vel dui. Proin tristique laoreet lacus, ac consectetur erat feugiat in. In malesuada arcu vitae dolor vulputate mollis. Nam hendrerit risus diam, nec ultrices turpis lacinia sed. Maecenas tincidunt ornare tincidunt. Nulla facilisi. Etiam ullamcorper vestibulum efficitur. Curabitur cursus, nisl sit amet lobortis facilisis, nisi mi eleifend nibh, ac pretium sapien elit et augue. Suspendisse hendrerit ullamcorper nisl, ac placerat nisl eleifend id. Fusce luctus mi a nunc molestie placerat. Mauris orci quam, fermentum sed consequat a, dictum ut risus. Curabitur laoreet arcu purus, sed tincidunt mi consequat aliquet. Vestibulum fermentum leo a orci lacinia ornare.

Vestibulum eleifend porta magna, ac luctus quam porttitor eget. In hac habitasse platea dictumst. Nam congue, augue ut lacinia volutpat, turpis diam convallis nisi, sed feugiat risus dolor sit amet mi. Vivamus eu leo elementum, pulvinar nisl quis, vulputate magna. Etiam imperdiet diam magna, et laoreet quam sodales pretium. Sed pretium faucibus turpis nec vestibulum. Nulla et hendrerit ligula, quis tempus ligula. Donec lobortis at dui vulputate hendrerit. Nulla finibus sagittis enim ut condimentum.

Quisque sapien massa, aliquet sit amet mollis nec, dignissim eget ligula. Donec ipsum lorem, ultricies et lacus vel, luctus ultrices dui. Nunc felis nulla, cursus eget sapien quis, molestie feugiat nibh. Duis eleifend dictum tempus. Ut sit amet ex sed libero dapibus elementum eu sit amet leo. Mauris mollis diam quis nisi iaculis, quis tincidunt sem vestibulum. Morbi non interdum risus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut ultrices lectus in mauris ornare, a gravida lorem ullamcorper. Cras condimentum efficitur dui, vitae bibendum erat egestas sed. Morbi finibus, sem sit amet rhoncus consectetur, dui mi placerat sapien, in varius tortor nisl semper risus. Sed gravida turpis sit amet augue placerat porta. Donec vulputate mollis mi sit amet aliquam. Praesent et pellentesque est. Donec vel magna mauris.

In eu commodo quam, fermentum imperdiet justo. Mauris gravida odio et faucibus porttitor. Curabitur vitae sem in risus fringilla varius sit amet ut mauris. Sed nec blandit ipsum. Phasellus vitae justo sed magna rhoncus eleifend ac molestie urna. Proin arcu augue, varius sit amet ex sit amet, efficitur condimentum orci. In hac habitasse platea dictumst. Suspendisse a ullamcorper justo, ut fringilla metus. Donec lacinia venenatis erat, sit amet blandit mi molestie eget. Vestibulum felis urna, venenatis nec ornare a, dapibus ut nunc. Morbi auctor quam sed purus congue, id cursus urna fermentum. Morbi cursus congue metus, non ultricies risus sollicitudin quis. Mauris tempus pharetra elit vitae mattis. Nam et aliquet purus.

Nullam feugiat lacus ac euismod bibendum. Sed a turpis congue, sodales arcu et, efficitur massa. Suspendisse eget efficitur lacus. Donec tempus mi ac velit consectetur, rutrum egestas leo auctor. Integer ex leo, consequat efficitur eros id, commodo suscipit lectus. Etiam gravida massa sapien, in vestibulum quam posuere id. Maecenas laoreet, est in posuere pharetra, nisi lacus consequat justo, nec lobortis augue magna ac metus. Aenean id massa venenatis, congue eros in, fermentum metus. Suspendisse quam neque, molestie vitae neque nec, vehicula tristique libero. Vivamus ultrices risus felis, ut scelerisque libero accumsan nec. Sed vel leo id orci tincidunt suscipit in at libero.

Proin ac iaculis lectus, in laoreet elit. Pellentesque porttitor ipsum eget pellentesque dignissim. Maecenas rhoncus, odio eget feugiat interdum, lacus massa ultricies leo, vel consequat ipsum tellus in lacus. Sed fringilla sapien ut erat vehicula, nec fermentum enim imperdiet. Quisque cursus condimentum leo a convallis. Nam luctus, augue varius congue pellentesque, metus eros vestibulum purus, ut venenatis massa eros in risus. Fusce dui augue, malesuada a porta ac, dapibus eget dui. Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec ligula nulla, ultricies eu arcu viverra, posuere malesuada enim. Quisque dolor elit, tincidunt et gravida sed, euismod a nibh. Sed ut neque id ex consequat gravida. Vivamus porta metus at enim pretium, ac commodo nisi eleifend. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vivamus aliquam lacus a leo commodo tincidunt. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec accumsan, diam non fermentum faucibus, quam nunc efficitur massa, in aliquam dui quam vel eros.

Vestibulum lacus odio, tempus et mi sit amet, feugiat tempus tortor. Sed ornare molestie ante, id hendrerit sem malesuada a. Sed aliquet ut turpis sed euismod. Donec eu leo ligula. Nam feugiat condimentum dolor, quis pharetra elit viverra id. Pellentesque id lobortis diam, quis mollis orci. Aliquam tristique, felis vitae fringilla ultricies, ipsum elit dignissim dolor, ac ultrices mi felis in odio. Vestibulum interdum sollicitudin dolor id mollis. Proin massa ex, pretium et luctus sit amet, euismod et dui. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla facilisi. Curabitur convallis interdum placerat.

Donec eu ultricies lacus, ut lacinia libero. Maecenas a auctor ante. Integer accumsan aliquam dapibus. Sed nec nisl massa. Praesent non vehicula lacus. Donec feugiat cursus est, sit amet placerat odio laoreet ut. Phasellus fringilla rutrum dolor. Donec orci felis, varius sit amet orci eu, tincidunt sollicitudin metus. Proin vel luctus leo, non dictum orci. Curabitur sollicitudin, lacus quis malesuada aliquet, dui tortor egestas arcu, sed varius nulla lorem nec urna.

In nibh massa, ultricies vitae pretium eu, pretium a velit. Nunc laoreet erat sit amet lacus vehicula, sed lacinia nunc malesuada. Donec gravida vehicula tellus, id faucibus nisi. Ut et sapien magna. Duis interdum egestas commodo. Etiam ex nisi, ultricies in ex at, fermentum eleifend elit. Nam semper eros sapien, lobortis dapibus velit tincidunt nec. Duis iaculis dictum ultrices. Sed bibendum ultrices massa sit amet elementum. Ut ultricies orci dictum, suscipit dui eu, fringilla est. Vestibulum diam neque, dapibus nec dui vitae, faucibus aliquet dolor. Nam in luctus ipsum. Donec libero sapien, sollicitudin at elementum id, vulputate in neque. Quisque et lacus et nulla condimentum vestibulum. In pulvinar arcu quis neque lacinia accumsan vel a sapien. Ut nec libero non risus scelerisque commodo.

Mauris nec massa semper, fringilla arcu eu, accumsan massa. Etiam ac dolor quis ligula sollicitudin tincidunt nec at tellus. Etiam placerat urna id orci volutpat suscipit. Pellentesque bibendum sagittis viverra. Aenean et egestas neque. Vestibulum risus nisi, viverra et euismod quis, cursus vitae purus. Vivamus ultricies quis metus at pellentesque.

Mauris posuere porttitor venenatis. Nulla augue arcu, suscipit a magna in, malesuada semper nisi. Morbi fringilla sollicitudin eleifend. Suspendisse et urna mauris. Morbi vulputate pretium quam, quis interdum metus viverra nec. Etiam quis lectus lobortis, consectetur eros ac, rutrum sem. Etiam porta, ante vitae vulputate tincidunt, tortor metus imperdiet ipsum, vitae luctus sapien augue non mauris. Donec at venenatis leo, non vulputate tortor. Aenean viverra, odio at porta ullamcorper, mi velit euismod nulla, non pretium felis mauris vel turpis. Nulla sagittis ut arcu ac cursus. Etiam justo odio, pulvinar in venenatis nec, sollicitudin ac lacus. Vivamus maximus ex eu risus pellentesque, at fringilla velit condimentum.

Sed neque tellus, molestie nec elementum ut, consequat quis metus. Aenean non turpis dictum, volutpat elit et, faucibus lacus. Duis eu gravida.`;

export const STRING_SIZE_15090_BYTES = STRING_SIZE_7546_BYTES + STRING_SIZE_7546_BYTES;
